name: purgecss

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
    - run: npm i purgecss
    - run: npx purgecss --css src/tailwind.css --content "*.md" "*.html" "*.js" --output assets/css/
    - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Dist
